apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - wedding-share-namespace.yaml
  - wedding-share-ingressroute.yaml
  - wedding-share-release.yaml
  - wedding-share-secret.yaml