---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cura
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/volsync
    - ../../../components/gatus/internal
    - ../../../components/gatus/external
  interval: 1h
  path: ./apps/base/cura
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: *app
      CAPACITY: 5Gi
      GATUS_PORT: "3000"
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: &namespace cura
  timeout: 5m
  wait: false