apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflared-namespace.yaml
  - ./cloudflared-secret.yaml
  - ./cloudflared-release.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true