apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cura-ingressroute
  annotations:
    gethomepage.dev/href: "https://${SUBDOMAIN:=cura}.hephaestus.markmk.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Cura"
    gethomepage.dev/description: "3D printer slicing software"
    gethomepage.dev/app: cura
    gethomepage.dev/group: "Tools"
    gethomepage.dev/icon: "https://curaslicer.com/wp-content/uploads/2024/10/cura-icon.png"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`${SUBDOMAIN:=cura}.hephaestus.markmk.com`)
      kind: Rule
      services:
        - name: cura
          port: 3000